core/urls.py
from django.contrib import admin
from django.conf.urls import handler404, handler500
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('srm/', include('srm.urls')),
    path('account/', include('account.urls')),
    path('classroom/', include('classroom.urls')),
    path('forum/', include('forum.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('', include('landing.urls')),
    path('classroom/', include('classroom.urls')),
    path('forum/', include('forum.urls')),
)

handler404 = 'landing.views.error_404'
handler500 = 'landing.views.error_500'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

srm/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("select2/", include("django_select2.urls")),
    path('students/', views.StudentListView.as_view(), name='leads'),
    path('', views.personal, name='personal'),
    path('leads_add/', views.lead_add, name='lead_add'),
    path('leads/<int:pk>/', views.leads_detail, name='leads_detail'),
    path('leads/delete/<int:pk>', views.lead_delete, name='lead_delete'),
    path('leads/', views.StudentList.as_view(), name='students'),
    path('students/<int:pk>/', views.student_detail, name='student_detail'),
    path('students/delete/<int:pk>/', views.student_delete, name='student_delete'),
    path('students_add/', views.student_add, name='student_add'),
    path('administrator/', views.IncomeListView.as_view(), name='income_list'),
    path('income_detail/<int:pk>/', views.income_detail, name='income_detail'),
    path('income_add/', views.income_add, name='income_add'),
    path('income_add_for_manager/', views.income_add_for_manager, name='income_add_for_manager'),
    path('income_list/delete/<int:pk>/', views.income_delete, name='income_delete'),
    path('expenses_list/', views.ExpenseListView.as_view(), name='expenses_list'),
    path('expense_detail/<int:pk>/', views.expense_detail, name='expense_detail'),
    path('expense_add/', views.expense_add, name='expense_add'),
    path('expense_delete/<int:pk>', views.expense_delete, name='expense_delete'),
    path('manager/', views.manager, name='manager'),
    path('debtor/', views.Debtor.as_view(), name='debtor'),
    path('admin_choice/', views.admin_choice, name='admin_choice'),
    path('incomes/', views.IncomesView.as_view(), name='incomes'),
]

srm/models.py
from decimal import Decimal

from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.html import format_html
from django.core.exceptions import ValidationError
from datetime import datetime


class Role(models.Model):
    title = models.CharField(max_length=70, verbose_name='Название')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Роль'
        verbose_name_plural = 'Роли'


class StudyingTime(models.Model):
    title = models.CharField(max_length=15, verbose_name='Название')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Время обучения'
        verbose_name_plural = 'Время обучения'


class LearningFormat(models.Model):
    title = models.CharField(max_length=50, verbose_name='Название')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Формат обучения'
        verbose_name_plural = 'Форматы обучения'


class Course(models.Model):
    title = models.CharField(max_length=123, verbose_name=('Название'))
    created_date = models.DateTimeField(auto_now_add=True, verbose_name=('Дата создания'))
    is_active = models.BooleanField(default=True, verbose_name=('Активен'))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Курс'
        verbose_name_plural = 'Курсы'


class Employee(models.Model):
    full_name = models.CharField(max_length=123, verbose_name='ФИО')
    image = models.ImageField(upload_to='media/image', verbose_name='Фотография')
    role = models.ForeignKey(Role, on_delete=models.CASCADE, verbose_name='Роль')
    salary = models.DecimalField(decimal_places=2, max_digits=12, default=0.00, verbose_name='Зарплата')
    description = models.TextField(verbose_name=('Описание для Лэндинга'), blank=True, null=True)
    course = models.ManyToManyField(Course, verbose_name='Курс', blank=True, null=True)
    studying_time = models.ManyToManyField(StudyingTime, verbose_name='Время обучения', blank=True, null=True)
    format = models.ManyToManyField(LearningFormat, verbose_name='Формат обучения', blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_active = models.BooleanField(default=True, verbose_name='Активен')

    def course_names(self):
        return " %s" % (", ".join([formats.title for formats in self.course.all()]))

    def format_names(self):
        return " %s" % (", ".join([formats.title for formats in self.format.all()]))

    def studying_time_names(self):
        return " %s" % (", ".join([formats.title for formats in self.studying_time.all()]))

    def __str__(self):
        return f'{self.full_name} | {self.course_names()} | {self.studying_time_names()} | {self.format_names()}'

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'


class Currency(models.Model):
    title = models.CharField(max_length=40, verbose_name='Название')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Валюта'
        verbose_name_plural = 'Валюты'


class PaymentMethod(models.Model):
    title = models.CharField(max_length=70, verbose_name='Название')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Способ оплаты'
        verbose_name_plural = 'Способы оплаты'


class Student(models.Model):
    full_name = models.CharField(max_length=80, verbose_name=('ФИО'))
    phone_number = models.CharField(verbose_name=('Номер телефона'), max_length=15)
    course = models.ForeignKey(
        Course,
        on_delete=models.CASCADE,
        verbose_name='Курс',
        related_name='student')
    teacher = models.ForeignKey(Employee, on_delete=models.CASCADE, verbose_name='Ментор', blank=True, null=True)
    studying_time = models.PositiveSmallIntegerField(
        choices=(
            (1, 'Утро'),
            (2, 'День'),
            (3, 'Вечер'),
            (4, 'Ночь'),
        ),
        verbose_name='Время обучения',
        blank=True,
        null=True
    )
    format = models.ForeignKey(LearningFormat, on_delete=models.CASCADE, verbose_name='Формат обучения', blank=True, null=True)
    certificate = models.PositiveSmallIntegerField(default=0, verbose_name='Сертификат')
    url = models.URLField(blank=True, null=True)
    total_payment = models.DecimalField(
        decimal_places=2,
        max_digits=12,
        default=0.00,
        verbose_name='Общая оплата',
        blank=True,
        null=True)
    last_payment_date = models.DateField(verbose_name='Дата последней оплаты', blank=True, null=True)
    remainder = models.DecimalField(
        decimal_places=2,
        max_digits=12,
        default=0.00,
        verbose_name='Остаток')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)
    is_graduate = models.BooleanField(default=False, verbose_name='Выпускник')
    created_date = models.DateField(auto_now_add=True, verbose_name='Дата создания')

    # def save(self, *args, **kwargs):
    #     if self.remainder == 0:
    #         remainder = Decimal(str(self.remainder))
    #         remainder -= Decimal(str(self.total_payment))
    #     return super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.full_name}  | {self.teacher} | {self.studying_time} | {self.format}'

    class Meta:
        verbose_name = 'Студент'
        verbose_name_plural = 'Студенты'


class Expense(models.Model):
    title = models.CharField(max_length=123, verbose_name='Название')
    value = models.DecimalField(decimal_places=2, max_digits=12, default=0.00, verbose_name='Цена')
    flow_type = models.PositiveSmallIntegerField(
        choices=(
            (1, 'Постоянный'),
            (2, 'Одноразовый'),
            (3, 'Сотрудник'),
            (4, 'Возврат'),
        ),
        verbose_name='Тип расхода'
    )
    date_of_payment = models.DateField(verbose_name='Дата')
    created_date = models.DateField(auto_now_add=True, verbose_name='Дата создания')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Расходы'
        verbose_name_plural = 'Расходы'


class Income(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, verbose_name='Студент')
    value = models.DecimalField(decimal_places=2, max_digits=12, default=0.00, verbose_name='Цена')
    payment_method = models.ForeignKey(
                PaymentMethod,
                on_delete=models.CASCADE,
                verbose_name='Способ оплаты',
                related_name='incomes',
            )
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE, verbose_name='Валюта', blank=True, null=True)
    date_of_payment = models.DateField(verbose_name='Дата оплаты')
    created_date = models.DateField(auto_now_add=True, verbose_name='Дата создания')

    def __str__(self):
        return str(self.student)

    def save(self, *args, **kwargs):
        student = self.student
        student.total_payment += self.value
        student.last_payment_date = datetime.now().date()
        student.remainder -= self.value
        student.save()
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Доходы'
        verbose_name_plural = 'Доходы'


class Lead(models.Model):
    full_name = models.CharField(max_length=80, verbose_name=('ФИО'))
    phone_number = models.CharField(max_length=15, verbose_name=('Номер телефона'))
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name=('Курс'), blank=True, null=True)
    description = models.TextField(verbose_name=('Описание'), blank=True, null=True)
    is_add = models.BooleanField(default=False, verbose_name=('Добавить'))
    created_date = models.DateTimeField(auto_now_add=True, verbose_name=('Дата создания'))

    def __str__(self):
        return self.full_name

    # def clean(self):
    #     if self.is_add == True:
    #         if not self.course:
    #             raise ValidationError({'course': 'На какой курс хочет записаться Лид'})
    #     return super(Lead, self).clean()
    #
    # def save(self, *args, **kwargs):
    #     if self.is_add == True:
    #         Student.objects.create(
    #             full_name=self.full_name,
    #             phone_number=self.phone_number,
    #             course=self.course,
    #         )
    #     return super().save(*args, *kwargs)
    def create_student(self):
        if self.is_add == True:
            student = Student.objects.create(
                full_name=self.full_name,
                phone_number=self.phone_number,
                course=self.course,
                description=self.description
            )
            return student
        return None

    def clean(self):
        if self.is_add == True:
            if not self.course:
                raise ValidationError({'course': 'На какой курс хочет записаться Лид'})
        return super(Lead, self).clean()

    def save(self, *args, **kwargs):
        self.create_student()
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Лид'
        verbose_name_plural = 'Лиды'

srm/forms.py
from django import forms
from .models import Lead, Student, Income, Expense, Course, Employee
from django_select2 import forms as s2forms


class StudentWidget(s2forms.ModelSelect2Widget):
    search_fields = [
        "full_name__iregex",
    ]


class TeacherWidget(s2forms.ModelSelect2Widget):
    search_fields = [
        "full_name__iregex",
    ]


class LeadForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ['full_name', 'phone_number', 'course', 'is_add', 'description']


class StudentForm(forms.ModelForm):
    last_payment_date = forms.DateField(widget=forms.widgets.DateInput(
        attrs={'type': 'date', 'placeholder': 'yyyy-mm-dd (DOB)', 'class': 'form-control'}),
        required=False,
        label='Дата последней оплаты'
    )
    remainder = forms.DecimalField(label='Общая оплата за курс')
    teacher = forms.ModelChoiceField(
        queryset=Employee.objects.all(),
        widget=TeacherWidget,
        label='Ментор'
    )

    class Meta:
        model = Student
        fields = ['full_name', 'phone_number', 'course', 'teacher', 'studying_time', 'format', 'certificate', 'url', 'is_graduate', 'remainder', 'description']


class IncomeForm(forms.ModelForm):
    student = forms.ModelChoiceField(
        queryset=Student.objects.all(),
        widget=StudentWidget,
        label='Студент'
    )
    date_of_payment = forms.DateField(widget=forms.widgets.DateInput(
        attrs={'type': 'date', 'placeholder': 'yyyy-mm-dd (DOB)', 'class': 'form-control'}),
        label='Дата оплаты'
    )

    class Meta:
        model = Income
        fields = ['student', 'value', 'payment_method', 'currency', 'date_of_payment']
        # widgets = {
        #     "student": StudentWidget,
        # }


class ExpenseForm(forms.ModelForm):
    date_of_payment = forms.DateField(widget=forms.widgets.DateInput(
        attrs={'type': 'date', 'placeholder': 'yyyy-mm-dd (DOB)', 'class': 'form-control'}),
        label='Дата'
    )

    class Meta:
        model = Expense
        fields = ['title', 'value', 'flow_type', 'date_of_payment']

srm/templates/srm/debtors.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block nav %}
  <!-- ***** Header Area Start ***** -->
  <header class="header-area header-sticky wow slideInDown" data-wow-duration="0.75s" data-wow-delay="0s">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav class="main-nav">
            <!-- ***** Logo Start ***** -->
            <a href="{% url 'index' %}" class="logo">
                <h4 style="color: black;"><br><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lightbulb-fill" viewBox="0 0 16 16">
  <path d="M2 6a6 6 0 1 1 10.174 4.31c-.203.196-.359.4-.453.619l-.762 1.769A.5.5 0 0 1 10.5 13h-5a.5.5 0 0 1-.46-.302l-.761-1.77a1.964 1.964 0 0 0-.453-.618A5.984 5.984 0 0 1 2 6zm3 8.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1l-.224.447a1 1 0 0 1-.894.553H6.618a1 1 0 0 1-.894-.553L5.5 15a.5.5 0 0 1-.5-.5z"/>
</svg> LightCode</h4>
            </a>
            <!-- ***** Logo End ***** -->
            <!-- ***** Menu Start ***** -->
            <a class='menu-trigger'>
                <span>Menu</span>
            </a>
            <!-- ***** Menu End ***** -->
          </nav>
        </div>
      </div>
    </div>
  </header>
  <!-- ***** Header Area End ***** -->
{% endblock nav %}
{% block content %}
<br><br><br><br><br><br><br><br><br>
<div class="container">
  <a style="font-size: 22px;" href="{% url 'admin_choice' %}"><i class="fa fa-arrow-left"></i>Назад </a>
</div>
<center>
    {{ filterset.form.media.css }}
  <h1 style="color: blue;">Должники</h1>
  <br>
  <br>
  <h3>Фильтрация для Студентов</h3>
    <div class="container mt-3" style="width: 55%; fon-size: 10px;">
  <form method="get" id="incomes">
<!--    {{ filter.form.as_p }}-->
    <div class="row" >
      <div class="col-6" >
        {{ filterset.form.course|as_crispy_field }}
      </div>
      <div class="col-6" >
        {{ filterset.form.is_graduate|as_crispy_field }}
      </div>
      <div class="col-6" >
        {{ filterset.form.studying_time|as_crispy_field }}
      </div>
       <div class="col-6" >
        {{ filterset.form.format|as_crispy_field }}
      </div>
    </div>
    <div class="col-6" >
        {{ filterset.form.teacher|as_crispy_field }}
      </div>
    <div class="col-6" >
        {{ filterset.form.created_date|as_crispy_field }}
      </div>
    <button type="submit">Применить фильтр</button>
</form>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        {{ filterset.form.media.js }}
  </div>


<!--    <form method="POST" action=".">-->
<!--  {% csrf_token %}-->
<!-- {{ form.as_p }}-->
<!--<button type="submit">Сохранить</button>-->
<!--  </form>-->
    <h2>Должники</h2>
         <h3>{{ total_debtors }}</h3>
  <br>
  <br>
  <br>
  <hr style="height: 2px; color: black;" >

    <h3>Студенты</h3>
  <br>
<style>
  table, th, td {
    border: 1px solid black;
  }
</style>
<!--<table class="table table-bordered">-->
<!--  <tbody>-->
<!--    <tr>-->
<!--      <th style="text-align: center; margin: 0 10px;" >ФИО</th>-->
<!--      <th style="text-align: center; margin: 0 10px;" >Номер телефона</th>-->
<!--      <th style="text-align: center; margin: 0 10px;" >Курс</th>-->
<!--      <th style="text-align: center; margin: 0 10px;" >Ментор</th>-->
<!--      <th style="text-align: center; margin: 0 10px;" >Формат обучения</th>-->
<!--      <th style="text-align: center; margin: 0 10px;" >Сертификат</th>-->
<!--      <th style="text-align: center; margin: 0 10px;" >URL</th>-->
<!--      <th style="text-align: center; margin: 0 10px;" >Время обучения</th>-->
<!--      <th style="text-align: center; margin: 0 10px;" >Выпускник</th>-->
<!--      <th style="text-align: center; margin: 0 10px;" >Дата создания</th>-->
<!--      <th style="text-align: center; margin: 0 10px;" >Общая оплата</th>-->
<!--      <th style="text-align: center; margin: 0 10px;" >Остаток</th>-->
<!--      <th style="text-align: center; margin: 0 10px;" >Дата последней оплаты</th>-->
<!--    </tr>-->
<!--    {% for student in students %}-->
<!--    <tr>-->
<!--      <td style="text-align: center; margin: 0 10px;"><a href="{% url 'student_detail' student.id %}" >{{ student.full_name }}</a></td>-->
<!--      <td style="text-align: center; margin: 0 10px;" >{{ student.phone_number }}</td>-->
<!--      {% if student.course %}-->
<!--        <td style="text-align: center; margin: 0 10px;" >{{ student.course }}</td>-->
<!--      {% else %}-->
<!--        <td style="text-align: center; margin: 0 10px;" >{{ student.teacher }}</td>-->
<!--      {% endif %}-->
<!--        <td style="text-align: center; margin: 0 10px;" ></td>-->
<!--      {% if student.format %}-->
<!--        <td style="text-align: center; margin: 0 10px;" >{{ student.format }}</td>-->
<!--      {% else %}-->
<!--        <td style="text-align: center; margin: 0 10px;" ></td>-->
<!--      {% endif %}-->
<!--      <td style="text-align: center; margin: 0 10px;" >{{ student.certificate }}</td>-->
<!--      {% if student.url %}-->
<!--        <td style="text-align: center; margin: 0 10px;" >{{ student.url }}</td>-->
<!--      {% else %}-->
<!--        <td style="text-align: center; margin: 0 10px;" ></td>-->
<!--      {% endif %}-->
<!--      {% if student.time %}-->
<!--        <td style="text-align: center; margin: 0 10px;" >{{ student.get_studying_time_display }}</td>-->
<!--      {% else %}-->
<!--        <td style="text-align: center; margin: 0 10px;" ></td>-->
<!--      {% endif %}-->
<!--      <td style="text-align: center; margin: 0 10px;" >{{ student.is_graduate }}</td>-->
<!--      <td style="text-align: center; margin: 0 10px;" >{{ student.created_date }}</td>-->
<!--        <td style="text-align: center; margin: 0 10px;" >{{ student.total_payment }}</td>-->
<!--      <td style="text-align: center; margin: 0 10px;" >{{ student.remainder }}</td>-->
<!--      {% if student.last_payment_date %}-->
<!--        <td style="text-align: center; margin: 0 10px;" >{{ student.last_payment_date }}</td>-->
<!--      {% else %}-->
<!--        <td style="text-align: center; margin: 0 10px;" ></td>-->
<!--      {% endif %}-->
<!--      <td><a href="{% url 'student_delete' student.id %}">Удалить</a></td>-->
<!--    </tr>-->
<!--    {% endfor %}-->
<!--  </tbody>-->
<!--</table>-->
  <div class="container mt-3" style="width: 70%; fon-size: 10px;">
  <div class="row row-cols-1 row-cols-md-3 g-4">
  <table class="table table-bordered">
  <tbody>
    <tr>
      <th style="text-align: center; margin: 0 10px;" >ФИО</th>
      <th style="text-align: center; margin: 0 10px;" >Номер телефона</th>
      <th style="text-align: center; margin: 0 10px;" >Ментор</th>
      <th style="text-align: center; margin: 0 10px;" >Дата создания</th>
      <th style="text-align: center; margin: 0 10px;" >Общая оплата</th>
      <th style="text-align: center; margin: 0 10px;" >Остаток</th>
      <th style="text-align: center; margin: 0 10px;" >Дата последней оплаты</th>
    </tr>
    {% for student in students %}
    <tr>
      <td style="text-align: center; margin: 0 10px;"><a href="{% url 'student_detail' student.id %}" >{{ student.full_name }}</a></td>
      <td style="text-align: center; margin: 0 10px;" >{{ student.phone_number }}</td>
        <td style="text-align: center; margin: 0 10px;" >{{ student.teacher }}</td>
      <td style="text-align: center; margin: 0 10px;" >{{ student.created_date }}</td>
        <td style="text-align: center; margin: 0 10px;" >{{ student.total_payment }}</td>
      <td style="text-align: center; margin: 0 10px;" >{{ student.remainder }}</td>
      {% if student.last_payment_date %}
        <td style="text-align: center; margin: 0 10px;" >{{ student.last_payment_date }}</td>
      {% else %}
        <td style="text-align: center; margin: 0 10px;" ></td>
      {% endif %}
      <td><a href="{% url 'student_delete' student.id %}">Удалить</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
  </div>
  </div>
  <br>
<br>
<br>
</center>
{% endblock %}

srm/templates/srm/expense_detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block nav %}
  <!-- ***** Header Area Start ***** -->
  <header class="header-area header-sticky wow slideInDown" data-wow-duration="0.75s" data-wow-delay="0s">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav class="main-nav">
            <!-- ***** Logo Start ***** -->
            <a href="{% url 'index' %}" class="logo">
                <h4 style="color: black;"><br><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lightbulb-fill" viewBox="0 0 16 16">
  <path d="M2 6a6 6 0 1 1 10.174 4.31c-.203.196-.359.4-.453.619l-.762 1.769A.5.5 0 0 1 10.5 13h-5a.5.5 0 0 1-.46-.302l-.761-1.77a1.964 1.964 0 0 0-.453-.618A5.984 5.984 0 0 1 2 6zm3 8.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1l-.224.447a1 1 0 0 1-.894.553H6.618a1 1 0 0 1-.894-.553L5.5 15a.5.5 0 0 1-.5-.5z"/>
</svg> LightCode</h4>
            </a>
            <!-- ***** Logo End ***** -->
            <!-- ***** Menu Start ***** -->
            <a class='menu-trigger'>
                <span>Menu</span>
            </a>
            <!-- ***** Menu End ***** -->
          </nav>
        </div>
      </div>
    </div>
  </header>
  <!-- ***** Header Area End ***** -->
{% endblock nav %}
{% block content %}
<br><br><br><br><br><br><br><br><br>
<div class="container">
  <a style="font-size: 22px;" href="{% url 'income_list' %}"><i class="fa fa-arrow-left"></i>Назад </a>
</div>
<center>
    <h3>Расход</h3>
  <br>
<style>
  table, th, td {
    border: 1px solid black;
  }
</style>
  <table class="table table-bordered">
  <tbody>
    <tr>
      <th style="text-align: center; margin: 0 10px;" >Наименование расхода</th>
      <th style="text-align: center; margin: 0 10px;" >Значение</th>
      <th style="text-align: center; margin: 0 10px;" >Тип расхода</th>
      <th style="text-align: center; margin: 0 10px;" >Дата создания</th>
    </tr>
    <tr>
      <td style="text-align: center; margin: 0 10px;"><a href="{% url 'expense_detail' expense.id %}" >{{ expense.title }}</a></td>
      <td style="text-align: center; margin: 0 10px;" >{{ expense.value }}</td>
      <td style="text-align: center; margin: 0 10px;" >{{ expense.get_flow_type_display }}</td>
      <td style="text-align: center; margin: 0 10px;" >{{ expense.created_date }}</td>
        <td><a href="{% url 'expense_delete' expense.id %}">Удалить</a></td>
    </tr>
  </tbody>
</table>
  <br>
  <br>
  <br>
  <h4>Изменить объект</h4><br>
    <div class="container" style="width: 25%;">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-danger">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
        </div>
      <div class="container mt-3" style="width: 55%; fon-size: 10px;">
    <form method="POST" action=".">
  {% csrf_token %}
<!-- {{ form|crispy }}-->
        <div class="row" >
            <div class="col-6" >
                {{ form.title|as_crispy_field }}
            </div>
            <div class="col-6" >
                {{ form.value|as_crispy_field }}
            </div>

        </div>
      <div class="col-6" >
          {{ form.flow_type|as_crispy_field }}
      </div>
        <div class="col-6" >
            {{ form.date_of_payment|as_crispy_field }}
        </div>
<button type="submit">Сохранить</button>
  </form>
      </div>

</center>
{% endblock %}