core/urls.py
from django.contrib import admin
from django.conf.urls import handler404, handler500
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('srm/', include('srm.urls')),
    path('account/', include('account.urls')),
    path('classroom/', include('classroom.urls')),
    path('forum/', include('forum.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('', include('landing.urls')),
    path('classroom/', include('classroom.urls')),
    path('forum/', include('forum.urls')),
)

handler404 = 'landing.views.error_404'
handler500 = 'landing.views.error_500'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

landing/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('course-detail/<slug:slug>/', views.course_detail, name='course-detail'),
    path('employee_detail/<int:pk>/', views.employee_detail, name='employee_detail'),
    path('personal_area/', views.personal_area, name='personal_area'),
    path('category/', views.category_view, name='tutorials'),
    path('category/<slug:slug>/', views.category_detail, name='tutorial-detail'),
    path('tutorial-content/<slug:slug>/', views.theme_view, name='tutorial-content'),
    path('content-view/<slug:slug>/', views.content_view, name='content_view'),
    path('add-category/', views.add_category, name='add_category'),
    path('add-article/', views.add_article, name='add_article'),
    path('registration/', views.register_view, name='registration'),
    path('authentication/', views.authentication_view, name='authentication'),
    path('logout/', views.logout_view, name='exit'),
    path('add-url-stream/', views.add_url_stream, name='add_url_stream'),
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:pk>/', views.article_detail, name='article_detail'),
    path('article-delete/<int:pk>/', views.article_delete, name='article_delete'),
]

srm/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("select2/", include("django_select2.urls")),
    path('students/', views.StudentListView.as_view(), name='leads'),
    path('', views.personal, name='personal'),
    path('leads_add/', views.lead_add, name='lead_add'),
    path('leads/<int:pk>/', views.leads_detail, name='leads_detail'),
    path('leads/delete/<int:pk>', views.lead_delete, name='lead_delete'),
    path('leads/', views.StudentList.as_view(), name='students'),
    path('students/<int:pk>/', views.student_detail, name='student_detail'),
    path('students/delete/<int:pk>/', views.student_delete, name='student_delete'),
    path('students_add/', views.student_add, name='student_add'),
    path('administrator/', views.IncomeListView.as_view(), name='income_list'),
    path('income_detail/<int:pk>/', views.income_detail, name='income_detail'),
    path('income_add/', views.income_add, name='income_add'),
    path('income_add_for_manager/', views.income_add_for_manager, name='income_add_for_manager'),
    path('income_list/delete/<int:pk>/', views.income_delete, name='income_delete'),
    path('expenses_list/', views.ExpenseListView.as_view(), name='expenses_list'),
    path('expense_detail/<int:pk>/', views.expense_detail, name='expense_detail'),
    path('expense_add/', views.expense_add, name='expense_add'),
    path('expense_delete/<int:pk>', views.expense_delete, name='expense_delete'),
    path('manager/', views.manager, name='manager'),
    path('debtor/', views.Debtor.as_view(), name='debtor'),
    path('admin_choice/', views.admin_choice, name='admin_choice'),
    path('incomes/', views.IncomesView.as_view(), name='incomes'),
]

account/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from phonenumber_field.modelfields import PhoneNumberField


class MyUserManager(BaseUserManager):
    def create_user(self, phone_number, username, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """

        user = self.model(
            phone_number=phone_number,
            username=username
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, phone_number, username, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            phone_number=phone_number,
            username=username,
            password=password,

        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser, PermissionsMixin):
    # email = models.EmailField(
    #     verbose_name=('Адрес электронной почты'),
    #     max_length=255,
    #     unique=True,
    # )
    username = models.CharField(
        max_length=50,
        verbose_name='Имя пользователя',
        unique=True,
    )
    phone_number = PhoneNumberField(
        verbose_name=('Номер телефона'),
        unique=True
    )
    status = models.PositiveSmallIntegerField(
        choices=(
            (1, 'Простой пользователь'),
            (2, 'Студент'),
            (3, 'Менеждер'),
            (4, 'Ментор'),
            (5, 'Копирайтер'),
            (6, 'Модератор')
        ),
        default=1,
        verbose_name=('Статус')
    )
    created_date = models.DateField(auto_now_add=True, verbose_name='Дата создания аккаунта')
    is_active = models.BooleanField(
        default=True,
        verbose_name=('Пользователь активен?')
    )
    is_admin = models.BooleanField(
        default=False,
        verbose_name=('Админ')
    )
    is_banned = models.PositiveSmallIntegerField(
        choices=(
            (1, 'Ограничений нет'),
            (2, 'Забанен на время'),
            (3, 'Забанен навсегда'),
        ),
        default=1,
        verbose_name='Статус на ограничение'
    )
    objects = MyUserManager()

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['username', ]

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        """Does the user have a specific permission?"""
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        """Does the user have permissions to view the app `app_label`?"""
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        """Is the user a member of staff?"""
        # Simplest possible answer: All admins are staff
        return self.is_admin

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

landing/models.py
from django.db import models
from django.contrib.auth import get_user_model
from ckeditor.fields import RichTextField
from googletrans import Translator
from bs4 import BeautifulSoup


User = get_user_model()

translator = Translator(service_urls=[
            'translate.google.com',
            'translate.google.co.kr',
        ])


class StudyingTime(models.Model):
    title = models.CharField(max_length=50, verbose_name='Название')

    def save(self, *args, **kwargs):

        text_title = self.title

        ky_title = translator.translate(str(text_title), 'ky')
        # print(a.text)
        self.title_ky = ky_title.text

        super().save()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Время обучения'
        verbose_name_plural = 'Время обучения'


class CourseForLanding(models.Model):
    title = models.CharField(max_length=123, verbose_name=('Название'))
    slug = models.SlugField()
    cover = models.ImageField(upload_to='media/image/', verbose_name=('Обложка'))
    description = models.TextField(verbose_name=('Описание о языке'))
    studying_time = models.ManyToManyField(StudyingTime, verbose_name='Время обучения')
    format = models.ManyToManyField('srm.LearningFormat', verbose_name='Формат обучения')
    additional_info = models.TextField(verbose_name='Информация о курсе', blank=True, null=True)
    teacher = models.ForeignKey('srm.Employee', on_delete=models.PROTECT, verbose_name='Ментор')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name=('Дата создания'))
    is_active = models.BooleanField(default=True, verbose_name=('Активен'))

    def studying_time_names(self):
        return " %s" % (", ".join([formats.title for formats in self.studying_time.all()]))

    def format_names(self):
        return " %s" % (", ".join([formats.title for formats in self.format.all()]))

    def save(self, *args, **kwargs):

        text_title = self.title
        text_description = self.description
        text_additional_info = self.additional_info

        ky_title = translator.translate(str(text_title), 'ky')
        # print(a.text)
        self.title_ky = ky_title.text

        ky_description = translator.translate(str(text_description), 'ky')
        # print(a.text)
        self.description_ky = ky_description.text

        ky_additional_info = translator.translate(str(text_additional_info), 'ky')
        # print(a.text)
        self.additional_info_ky = ky_additional_info.text

        super().save()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Курс для Лэндинга'
        verbose_name_plural = 'Курс для Лэндинга'


class Review(models.Model):
    name = models.CharField(max_length=70, verbose_name='Имя')
    direction = models.CharField(max_length=50, verbose_name='Направление')
    description = models.TextField(verbose_name=('Описание'), max_length=515)
    created_date = models.DateTimeField(auto_now_add=True, verbose_name=('Дата создания'))

    def save(self, *args, **kwargs):

        text_name = self.name
        text_direction = self.direction
        text_description = self.description

        ky_name = translator.translate(str(text_name), 'ky')
        # print(a.text)
        self.name_ky = ky_name.text

        ky_direction = translator.translate(str(text_direction), 'ky')
        # print(a.text)
        self.direction_ky = ky_direction.text

        ky_description = translator.translate(str(text_description), 'ky')
        # print(a.text)
        self.description_ky = ky_description.text

        super().save()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'


class Section(models.Model):
    title = models.CharField(max_length=123, verbose_name='Название')
    slug = models.SlugField()
    id_section = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name='children')
    description = models.TextField(verbose_name='Описание для подраздела', blank=True, null=True)

    def save(self, *args, **kwargs):

        text_title = self.title
        text_description = self.description

        ky_title = translator.translate(str(text_title), 'ky')
        # print(a.text)
        self.title_ky = ky_title.text

        ky_description = translator.translate(str(text_description), 'ky')
        # print(a.text)
        self.description_ky = ky_description.text

        super().save()

    def __str__(self):
        full_path = [self.title]
        k = self.id_section
        while k is not None:
            full_path.append(k.title)
            k = k.id_section
        return ' -> '.join(full_path[::-1])

    class Meta:
        verbose_name = 'Раздел'
        verbose_name_plural = 'Разделы'


class Article(models.Model):
    teacher = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Ментор')
    topic_name = models.CharField(max_length=80, verbose_name='Название темы')
    slug = models.SlugField()
    body = RichTextField(verbose_name='Контент')
    section = models.ForeignKey(Section, on_delete=models.CASCADE, verbose_name='Раздел')
    created_date = models.DateField(auto_now_add=True, verbose_name='Дата создания')

    def __str__(self):
        return str(self.section)

    def save(self, *args, **kwargs):

        text_topic_name = self.topic_name

        ky_topic_name = translator.translate(str(text_topic_name), 'ky')
        self.topic_name_ky = ky_topic_name.text

        soup = BeautifulSoup(self.body, 'html.parser')
        text_body = [i.replace('.', '. ') for i in list(soup.stripped_strings)]
        dct = {i: translator.translate(i, 'ky').text for i in text_body}

        for k, v in dct.items():
            self.body_ky = self.body_ky.replace(k, v)

        user = self.teacher
        user.status = 4
        user.save()
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'


class SubscriptionToCourse(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    course = models.ForeignKey(Section, on_delete=models.CASCADE, verbose_name='Курс')
    created_date = models.DateField(auto_now_add=True, verbose_name='Дата создания')

    def __str__(self):
        return str(self.user)

    def save(self, *args, **kwargs):
        user = self.user
        if user.status == 2 or user.status == 1:
            user.status = 2
            user.save()
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Подписка на курс'
        verbose_name_plural = 'Подписка на курс'
        unique_together = ['user', 'course']


class Stream(models.Model):
    url = models.TextField(verbose_name='Ссылка на прямой эфир')
    start_time = models.DateTimeField(verbose_name='Время начала стрима')
    end_time = models.DateTimeField(verbose_name='Время окончания стрима')
    is_active = models.BooleanField(verbose_name='Актуально?')
    # def save(self, *args, **kwargs):
    #     # Получить все объекты Stream кроме текущего
    #     other_streams = Stream.objects.exclude(pk=self.pk)
    #     # Удалить все полученные объекты
    #     other_streams.delete()
    #     super(Stream, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Прямой эфир'
        verbose_name_plural = 'Прямой эфир'

landing/forms.py
import re

from django import forms
from .models import Section, Article, Stream
from ckeditor.widgets import CKEditorWidget
from django_select2 import forms as s2forms


class SectionWidget(s2forms.ModelSelect2Widget):
    search_fields = [
        "title__iregex",
    ]


class SectionForm(forms.ModelForm):

    def clean_slug(self):
        slug = self.cleaned_data['slug']
        if not re.match(r'^[-a-zA-Z0-9_/\\|#.+]+$', slug):
            raise forms.ValidationError('Invalid slug')
        return slug

    id_section = forms.ModelChoiceField(
        queryset=Section.objects.all(),
        widget=SectionWidget,
        required=False
    )

    class Meta:
        model = Section
        fields = ['title', 'slug', 'id_section', 'description']


class ArticleForm(forms.ModelForm):
    body = forms.CharField(widget=CKEditorWidget())
    # body_ky = forms.CharField(widget=CKEditorWidget(), label='На кыргызском (Не обязательное)', required=False)
    section = forms.ModelChoiceField(
        queryset=Section.objects.all(),
        widget=SectionWidget,
        label='Раздел'
    )

    class Meta:
        model = Article
        fields = ['topic_name', 'slug', 'section', 'body']


class StreamForm(forms.ModelForm):
    start_time = forms.DateTimeField(widget=forms.widgets.DateTimeInput(
        attrs={'type': 'datetime-local', 'placeholder': 'yyyy-mm-dd (DOB)', 'class': 'form-control'}))
    end_time = forms.DateTimeField(widget=forms.widgets.DateTimeInput(
        attrs={'type': 'datetime-local', 'placeholder': 'yyyy-mm-dd (DOB)', 'class': 'form-control'}))

    class Meta:
        model = Stream
        fields = ['url', 'start_time', 'end_time', 'is_active']

landing/templates/landing/404error.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

{% block content %}
<br><br><br>
<br><br><br>
<center>
    <div class="container mt-3" style="width: 55%; fon-size: 10px;">
        <h1>404</h1><br>
        <h4>{% trans 'К сожалению, запрашиваемая вами страница не может быть найдена. Вероятно, адрес страницы был неверно введен или страница была удалена.' %}</h4><br><br>
        <h6>{% trans 'Чтобы решить эту проблему, вы можете попробовать следующее' %}:<br><br>
            1: {% trans 'Проверьте правильность адреса страницы, чтобы убедиться, что он был правильно набран.' %}<br><br>
            2: {% trans 'Используйте поиск на сайте, чтобы найти нужную информацию.' %}<br><br>
            3: {% trans 'Перейдите на главную страницу сайта и попробуйте найти информацию, которую вы искали.' %}</h6><br><br>
        <button class="btn btn-primary"><a href="{% url 'index' %}" style="color: white;">{% trans 'Вернуться на главную страницу' %}</a></button>
    </div>
</center>
{% endblock %}

landing/templates/landing/add-category.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block nav %}
  <!-- ***** Header Area Start ***** -->
  <header class="header-area header-sticky wow slideInDown" data-wow-duration="0.75s" data-wow-delay="0s">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav class="main-nav">
            <!-- ***** Logo Start ***** -->
            <a href="{% url 'index' %}" class="logo">
                <h4 style="color: black;"><br><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lightbulb-fill" viewBox="0 0 16 16">
  <path d="M2 6a6 6 0 1 1 10.174 4.31c-.203.196-.359.4-.453.619l-.762 1.769A.5.5 0 0 1 10.5 13h-5a.5.5 0 0 1-.46-.302l-.761-1.77a1.964 1.964 0 0 0-.453-.618A5.984 5.984 0 0 1 2 6zm3 8.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1l-.224.447a1 1 0 0 1-.894.553H6.618a1 1 0 0 1-.894-.553L5.5 15a.5.5 0 0 1-.5-.5z"/>
</svg> LightCode</h4>
            </a>
            <!-- ***** Logo End ***** -->
            <!-- ***** Menu Start ***** -->
            <ul class="nav">
              <li class="scroll-to-section"><a href="{% url 'tutorials' %}">Туториалы</a></li>
              {% if not user.is_authenticated %}
              <li class="scroll-to-section"><a href="{% url 'registration' %}">Авторизация</a></li>
              {% endif %}
              {% if user.is_authenticated %}
                <li class="scroll-to-section"><a href="{% url 'exit' %}">Выйти</a></li>
                <li>
                    <div class="gradient-button">
                        <a id="modal_trigger" href="{% url 'personal_area' %}">&nbsp;<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                            <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0Zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4Zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10Z"/></svg>
                        </a>
                    </div>
                </li>
              {% endif %}
            </ul>
            <a class='menu-trigger'>
                <span>Menu</span>
            </a>
            <!-- ***** Menu End ***** -->
          </nav>
        </div>
      </div>
    </div>
  </header>
  <!-- ***** Header Area End ***** -->
{% endblock nav %}
{% block content %}
  <br>
<br><br><br><br><br>
<div class="container">
  <a style="font-size: 22px;" href="{% url 'tutorials' %}"><i class="fa fa-arrow-left"></i>Назад </a>
</div>
<br><br><br><br><br>
    {{ form.media.css }}
<center>
        <h3>Раздел</h3>
  <br>
    <div class="container" style="width: 25%;">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-danger">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
        </div>
      <div class="container mt-3" style="width: 55%; fon-size: 10px;">
    <form method="POST" action=".">
        {% csrf_token %}
        <div class="row" >
            <div class="col-6" >
                {{ form.title|as_crispy_field }}
            </div>
            <div class="col-6 d-none" >
                {{ form.slug|as_crispy_field }}
            </div>
            <div class="col-6" >
                {{ form.id_section|as_crispy_field }}
            </div>
        </div>
        <div class="col-6" >
                {{ form.description|as_crispy_field }}
            </div>
        <button type="submit">Сохранить</button>
        <br><br>
        <h5>Хотите сохранить и добавить другой объект?</h5>
        <select name="is_next">
            <option value="no">Нет</option>
            <option value="on">Да</option>
        </select>
  </form>
              <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    {{ form.media.js }}
      </div>
<script>
$(document).ready(function(){
    $('#id_title').on('keyup', function(){
        var title = $(this).val();
        var slug = '';
        if (/^[a-zA-Z0-9\/\\|#.+ ]+$/.test(title)) {
        slug = title.toLowerCase().replace(/[^a-zA-Z0-9\/\\|#.+]+/g, '-').replace(/[^\w\/\\|#.+]+/g, '-').replace(/[\\/|]/g, '_').replace(/#/g, '-sharp-').replace(/\+/g, '-plus-').replace(/\./g, '-dot-').replace(/ /g, '-').replace(/\//g, '(/)').replace(/\|/g, '(|)').replace(/\\/g, '(\\)').replace(/(^-|-$|_)+/g, '');
        } else if (/^[а-яА-Яa-zA-Z0-9\s]+$/.test(title)) {
            var rus_to_lat = {
                'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd', 'е': 'e', 'ё': 'yo', 'ж': 'zh', 'з': 'z', 'и': 'i', 'й': 'y', 'к': 'k', 'л': 'l', 'м': 'm', 'н': 'n', 'о': 'o', 'п': 'p', 'р': 'r', 'с': 's', 'т': 't', 'у': 'u', 'ф': 'f', 'х': 'h', 'ц': 'c', 'ч': 'ch', 'ш': 'sh', 'щ': 'sch', 'ъ': '', 'ы': 'y', 'ь': '', 'э': 'e', 'ю': 'yu', 'я': 'ya', ' ': '-', '#': '_sharp_', '+': '_plus_', '.': '_dot_', '/': '(/)', '|': '(|)', '\\': '(\\)'
            };
            slug = title.toLowerCase().replace(/[^\u0000-\u007E]/g, function(c) {
                return (typeof rus_to_lat[c] != 'undefined') ? rus_to_lat[c] : '-';
            }).replace(/[^\w]+/g, '-').replace(/[\\/|]/g, '_').replace(/(^-|-$|_)+/g, '');
        }
        $('#id_slug').val(slug);
    });
});
</script>


</center>
{% endblock %}

landing/templates/landing/personal_area.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<style>
  @media (max-width: 991px) {
    #right-images-for-hidden {
    display: none
    }
  }
</style>
<div style="background-image: url(https://oir.mobi/uploads/posts/2021-03/1616435811_9-p-belii-fon-gradient-11.png);">
<div id="about" class="about-us section">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 align-self-center">
          <div class="section-heading">
            <div class="col-lg-6">
              <div class="box-item">
                <h4><em>{% trans 'Личный кабинет' %}</em></h4>
              </div>
            </div>
              {% if user.is_banned == 2 or user.is_banned == 3%}
                  <div class="container" style="width: 75%;">
                      <div class="alert alert-danger">
                          {% if user.is_banned == 2 %}
                            <h7>{% trans 'Ваш аккаунт заблокирован на некоторое время из-за нарушения наших правил. Если у вас есть вопросы, свяжитесь с нами через форму обратной связи.' %}</h7>
                          {% endif %}
                          {% if user.is_banned == 3 %}
                            <h7>{% trans 'Ваш аккаунт заблокирован навсегда из-за нарушения наших правил. Пожалуйста, свяжитесь с нами, если у вас есть возражения.' %}</h7>
                          {% endif %}
                      </div>
                  </div>
              {% endif %}
            <h5>{% trans 'Добро пожаловать в ваш личный кабинет!' %}</h5>&nbsp;
            <h4>{{ user.username }}</h4>
            <h5>Статуc: {{ user.get_status_display }}</h5>
            <img src="{% static 'images/heading-line-dec.png' %}" alt="">
          </div>
          <div class="row">
            <div class="col-lg-6">
              <div class="box-item">
                <h3 style="color: blue;">Classroom</h3>
                {% for student in students %}
                  <a href="{% url 'render_class' student.classroom.id %}" style="color: black;"><h5>{{ student.classroom }}</h5></a>
                <h6>{% trans 'Ментор' %}:
        {% for teacher in student.classroom.teacher_set.all %}
            {{ teacher.teacher.username }}{% if not forloop.last %}, {% endif %}
        {% endfor %}
        </h6>
                  <hr>
                {% endfor %}
              </div>
            </div>
            <div class="col-lg-6">
              <div class="box-item">
                <h4 style="color: blue;">{% trans 'Онлайн курсы' %}</h4>
                {% for subscription in subscriptions %}
                  <a href="{% url 'tutorial-content' subscription.course.slug %}" style="color: black;"><h5>{{ subscription.course }}</h5></a>
            <h6>{% trans 'Ментор' %}: {{ subscription.course.article_set.first.teacher }}</h6>
            <hr>
        {% endfor %}
              </div>
            </div>
            <div class="col-lg-12">
              <p style="color: black;">{% trans 'Спасибо за интерес к школе IT-технологий LightCode! Мы предлагаем курсы по программированию, веб-разработке, аналитике данных и многому другому. Наши опытные преподаватели помогут вам освоить новые навыки и стать экспертом в выбранной области.' %} <br>{% trans 'У нас есть гибкая система обучения, которая позволяет выбрать удобное расписание и формат занятий. Вы можете выбрать индивидуальные занятия, групповые курсы или дистанционное обучение.' %} <br>{% trans 'Мы также предлагаем практические задания и проекты, которые помогут вам укрепить свои знания и подготовиться к реальным задачам на рынке труда.' %} <br>{% trans 'Присоединяйтесь к LightCode и начните свой путь в мире IT-технологий уже сегодня!' %}</p>
              <br>
              <div class="gradient-button">
                <a href="#">LightCode</a>
              </div>
              <span style="color: black;">{% trans 'Учитесь программированию вместе с LightCode' %} </span>
            </div>
          </div>
        </div>
        <div id="right-images-for-hidden" class="col-lg-6">
          <div class="right-image">
            <img src="{% static 'images/about-right-dec.png' %}" alt="">
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}